# Generated by Django 3.1.3 on 2023-06-14 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('duracion', models.IntegerField(default=0)),
                ('lanzamiento', models.TextField(default=' ')),
                ('autor', models.TextField(default='')),
                ('clasificacion', models.IntegerField(default=0)),
                ('pais', models.TextField(default='')),
                ('genero', models.TextField(default='')),
                ('album', models.TextField(default='')),
                ('disponible_Spotify', models.TextField(default='')),
                ('precio', models.FloatField(default=0)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Music', to='Music.musica')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
