apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexandrubites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alexandrubites
  template:
    metadata:
      labels:
        app: alexandrubites
    spec:
      containers:
      - image: okteto.dev/alexandrubites:latest
        name: alexandrubites
        envFrom:
        - configMapRef:
            name: alexandrubites-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: alexandrubites
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "alexandrubites"
    port: 8080
  selector:
    app: alexandrubites